import { db } from "../firebase/firebase.js";
import { collection,onSnapshot } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
const ids={fat:'dash-faturamento',ped:'dash-pedidos',and:'dash-andamento',tic:'dash-ticket',cli:'dash-clientes',tem:'dash-tempo'};
onSnapshot(collection(db,'pedidos'),snap=>{const pedidos=snap.docs.map(d=>({id:d.id,...d.data()}));render(pedidos)},e=>console.error(e));
function render(todos){const hoje=todos.filter(p=>mesmoDia(data(p),new Date()));const faturamento=hoje.reduce((s,p)=>s+n(p.total),0);set(ids.fat,moeda(faturamento));set(ids.ped,hoje.length);set(ids.and,hoje.filter(p=>!['entregue','finalizado'].includes(norm(p.status))).length);set(ids.tic,moeda(hoje.length?faturamento/hoje.length:0));const clientes=new Set(hoje.map(p=>tel(p)||nome(p).toLowerCase()).filter(Boolean));set(ids.cli,clientes.size);const tempos=hoje.map(p=>n(p.tempoPreparoMinutos)).filter(Boolean);set(ids.tem,tempos.length?Math.round(tempos.reduce((a,b)=>a+b,0)/tempos.length)+' min':'—');pagamentos(hoje);produtos(hoje);ultimos(todos)}
function pagamentos(ps){const m={Pix:0,Dinheiro:0,Crédito:0,Débito:0,Outros:0};ps.forEach(p=>m[forma(p.pagamento)]+=n(p.total));const max=Math.max(1,...Object.values(m));document.querySelector('#dash-pagamentos').innerHTML=Object.entries(m).map(([k,v])=>`<div class="barra-item"><div><span>${k}</span><strong>${moeda(v)}</strong></div><i><b style="width:${v/max*100}%"></b></i></div>`).join('')}
function produtos(ps){const m=new Map();ps.flatMap(p=>Array.isArray(p.itens)?p.itens:[]).forEach(i=>m.set(i.nome,(m.get(i.nome)||0)+n(i.quantidade||1)));const r=[...m].sort((a,b)=>b[1]-a[1]).slice(0,8);document.querySelector('#dash-produtos').innerHTML=r.length?r.map(([x,q],i)=>`<div><span>${i+1}. ${esc(x)}</span><strong>${q} un.</strong></div>`).join(''):'<p class="vazio">Nenhuma venda hoje.</p>'}
function ultimos(ps){const a=[...ps].sort((x,y)=>data(y)-data(x)).slice(0,8);document.querySelector('#dash-ultimos').innerHTML=a.length?a.map(p=>`<tr><td>#${p.numero||p.id.slice(0,6)}</td><td>${esc(nome(p))}</td><td>${esc(p.status||'Novo')}</td><td>${esc(p.pagamento||'—')}</td><td><strong>${moeda(p.total)}</strong></td></tr>`).join(''):'<tr><td colspan="5" class="vazio">Nenhum pedido.</td></tr>'}
function data(p){if(p.criadoEm?.toDate)return p.criadoEm.toDate();if(p.data){const [d,m,a]=String(p.data).split('/').map(Number);const [h,mi]=String(p.horario||'00:00').split(':').map(Number);return new Date(a||1970,(m||1)-1,d||1,h||0,mi||0)}return new Date(0)}function mesmoDia(a,b){return a.getFullYear()==b.getFullYear()&&a.getMonth()==b.getMonth()&&a.getDate()==b.getDate()}function nome(p){return typeof p.cliente==='object'?p.cliente?.nome||'Cliente':p.cliente||'Cliente'}function tel(p){return typeof p.cliente==='object'?p.cliente?.telefone||'':p.telefone||''}function forma(v){const x=String(v||'').toLowerCase();if(x.includes('pix'))return'Pix';if(x.includes('dinheiro'))return'Dinheiro';if(x.includes('crédito')||x.includes('credito'))return'Crédito';if(x.includes('débito')||x.includes('debito'))return'Débito';return'Outros'}function norm(v){return String(v||'').toLowerCase()}function n(v){return Number(v)||0}function moeda(v){return n(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
